services:
  web:
    build:
      context: .
      dockerfile: dockerfile.web
    ports:
      - "3002:3002"


  app:
    build:
      context: .
      dockerfile: dockerfile.app
    ports:
      - "3001:3001"




  prometheus-agent:
    image: prom/prometheus:latest
    container_name: prometheus-agent
    command:
      - --config.file=/etc/prometheus/prometheus-agent.yml
    volumes:
      - ./prometheus-agent.yml:/etc/prometheus/prometheus-agent.yml:ro
    depends_on:
      - "mimir-1"
      - "mimir-2"


  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning-datasources.yml:/etc/grafana/provisioning/datasources/provisioning-datasources.yml     


  load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "mimir-1"
      - "mimir-2"
    ports:
      - 9009:9009

  mimir-1:
    image: grafana/mimir:latest
    hostname : mimir-1
      - -config.file=/etc/mimir/mimir-config.yaml
    volumes:
      - ./mimir-config.yaml:/etc/mimir/mimir-config.yaml:ro

  mimir-2:
    image: grafana/mimir:latest
    hostname : mimir-2
    command:
      - -config.file=/etc/mimir/mimir-config.yaml
    volumes:
      - ./mimir-config.yaml:/etc/mimir/mimir-config.yaml:ro
# Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - "mimir-1"
      - "mimir-2"
