version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile.web
    ports:
      - "3002:3002"

  app:
    build:
      context: .
      dockerfile: dockerfile.app
    ports:
      - "3001:3001"
