version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile.web
    ports:
      - "3002:3002"


  app:
    build:
      context: .
      dockerfile: dockerfile.app
    ports:
      - "3001:3001"

 # Loki
  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - --config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml:ro

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning-datasources.yml:/etc/grafana/provisioning/datasources/provisioning-datasources.yml

# Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro